ALTER TABLE people
    ADD COLUMN pdob TIMESTAMP NOT NULL,
    ADD COLUMN pjoined TIMESTAMP NOT NULL,
    ADD COLUMN plastvisit TIMESTAMP NOT NULL,
    ADD COLUMN ppoints INT NOT NULL,
    ADD COLUMN pfavorites JSONB NOT NULL;
